//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ESMB_Intl_Admin_FB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Author
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Author()
        {
            this.TrueAnnouncements = new HashSet<TrueAnnouncement>();
        }
    
        public int AuthorID { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [DisplayName("Code")]
        public string AuthorCode { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [DisplayName("Name")]
        public string AuthorFLName { get; set; }

        public string AuthorLevel { get; set; }

        public string LoginErrorMessage { get; set; }

        [NotMapped]
        [DisplayName("Remember Me?")]
        public bool Remember { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrueAnnouncement> TrueAnnouncements { get; set; }

    }
}
