//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Dynamic;
using System.Security.Policy;
using System.Web;
namespace ESMB_Intl_Admin_FB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrueAnnouncement
    {
        

        public int AnnoID { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [DisplayName("Author")]
        public Nullable<int> AuthorID { get; set; }

        [Required(ErrorMessage = "This field is required")]
        public string Title { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [DataType(DataType.MultilineText)]
        public string Text { get; set; }

        public string Sender { get; set; }

        [Timestamp]
        public Nullable<int> Added { get; set; }

        [Timestamp]
        public Nullable<int> Updated { get; set; }

        public string Status { get; set; }
        public string ImgPath { get; set; }
        
        [NotMapped] //'cuz  ImageUpload is not in the SQL database
        public HttpPostedFileBase ImageUpload { get; set; } // 这个名字要跟 <input> 的 Name 一样

        public TrueAnnouncement()
        {
            ImgPath = "~/App_Files/Images/Jisoo-Lovelyz.jpg";
        }
    }
}
